- name: Make user to run docker without root perm
  hosts: "{{ host }}"
  vars:
    docker_group: docker
    docker_user: vagrant
  tasks:

  - name: Ensure group "docker" exists
    ansible.builtin.group:
      name: "{{ docker_group }}"
      state: present

  - name: Add the user to the docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    comment: John Doe
    append: yes
    group: "{{ docker_group }}"   
