- name: Hello World Sample
  vars_files: 
    - vars/vars.yml
  vars_prompt:
    - name: passwordqqqqqqqqqqqqq
      prompt: What is your password?
      private: no
      default: Defaultpassword
  hosts: "{{ host }}"
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ password }}"
